[project]
name = "MJCMLWorks"
version = "2020.0.0"
authors = [
  {name = "Jiacheng Ma", email = "jiachenm@andrew.cmu.edu"},
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["mlgorithms"]

